services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - /Users/pryadav/Desktop/data:/var/lib/mysql

  app:
    build: .
    container_name: fastapi-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:1234@db:3306/mydb